-- T-15 (breach notification & incident response, master-spec §16.7): adds the single additive
-- `IncidentEvent` table — the dedicated append-only incident log (build-brief item 4). One row per
-- lifecycle event (DECLARED | TRIAGED | CONTAINED | NOTIFIED | RESOLVED); there is deliberately no
-- separate "Incident" header row with a mutable status/severity column — current state is a
-- read-time projection folded from this ordered log
-- (src/services/security/incident/incident-projection.ts), never an UPDATEd column. No other model
-- is touched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same hand-authored-SQL convention established by 20260715140000_add_legal_hold,
-- 20260715212208_add_licensing_state_machine, and 20260716120000_t12_account_security. This mirrors
-- exactly what `prisma migrate dev` would generate from the schema diff introduced by this change.

-- CreateTable
CREATE TABLE "IncidentEvent" (
    "id"          TEXT NOT NULL,
    "incident_id" TEXT NOT NULL,
    "sequence"    INTEGER NOT NULL,
    "kind"        TEXT NOT NULL,
    "actor_id"    TEXT,
    "actor_role"  "Role",
    "payload"     JSONB NOT NULL,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "IncidentEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "IncidentEvent_incident_id_sequence_key" ON "IncidentEvent"("incident_id", "sequence");

-- CreateIndex
CREATE INDEX "IncidentEvent_incident_id_occurred_at_idx" ON "IncidentEvent"("incident_id", "occurred_at");

-- CreateIndex
CREATE INDEX "IncidentEvent_kind_occurred_at_idx" ON "IncidentEvent"("kind", "occurred_at");
