-- T-43 (WP07 — Accountability, Gamification & Motivation, master-spec §12). All ADDITIVE — no
-- existing table/column/enum is altered or dropped:
--   • `User.gated_complete_at` — the First-48 countdown's anchor timestamp (§12.2).
--   • `Contact.referred_by_contact_id` — referral attribution, a plain scalar self-pointer (§12.7),
--     matching this schema's established convention for a loosely-referenced attribution column
--     (see `ImportBatch`'s file-level note in schema.prisma).
--   • Five new tables: `GoalCommitmentCard` (§12.8), `StreakState` (§12.5), `NotificationPreference`
--     + `NotificationLog` (§12.6), `Referral` (§12.7). `MomentumEvent` / `Milestone` / `QuoteLibrary`
--     / `CourseProgress` already exist from earlier WP04/WP03 schema passes and are reused as-is.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset), following the same hand-authored-SQL
-- convention established by 20260717120000_t22_import_batch, 20260719100000_t38_optout_quiet_tcpa,
-- 20260720130000_t39_outreach_sequences, and others. This mirrors exactly what `prisma migrate dev`
-- would generate from the schema diff introduced by this change.

-- AlterTable (§12.2 First-48 anchor)
ALTER TABLE "User" ADD COLUMN "gated_complete_at" TIMESTAMPTZ(6);

-- AlterTable (§12.7 referral attribution)
ALTER TABLE "Contact" ADD COLUMN "referred_by_contact_id" TEXT;

-- CreateIndex
CREATE INDEX "Contact_referred_by_contact_id_idx" ON "Contact"("referred_by_contact_id");

-- CreateTable
CREATE TABLE "GoalCommitmentCard" (
    "id"                   TEXT NOT NULL,
    "user_id"              TEXT NOT NULL,
    "income_target"        TEXT,
    "promotion_timeline"   TEXT,
    "top_three_dreams"     JSONB,
    "financial_goals"      JSONB,
    "weekly_activity_math" JSONB,
    "created_at"           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"           TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "GoalCommitmentCard_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "GoalCommitmentCard_user_id_key" ON "GoalCommitmentCard"("user_id");

-- CreateIndex
CREATE INDEX "GoalCommitmentCard_user_id_idx" ON "GoalCommitmentCard"("user_id");

-- CreateTable
CREATE TABLE "StreakState" (
    "id"                      TEXT NOT NULL,
    "user_id"                 TEXT NOT NULL,
    "current_streak_days"     INTEGER NOT NULL DEFAULT 0,
    "longest_streak_days"     INTEGER NOT NULL DEFAULT 0,
    "last_qualifying_date"    TEXT,
    "grace_day_used_for_week" TEXT,
    "updated_at"              TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "StreakState_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "StreakState_user_id_key" ON "StreakState"("user_id");

-- CreateIndex
CREATE INDEX "StreakState_user_id_idx" ON "StreakState"("user_id");

-- CreateTable
CREATE TABLE "NotificationPreference" (
    "id"                        TEXT NOT NULL,
    "user_id"                   TEXT NOT NULL,
    "morning_briefing_enabled"  BOOLEAN NOT NULL DEFAULT true,
    "morning_briefing_time"     TEXT NOT NULL DEFAULT '07:00',
    "midday_motivation_enabled" BOOLEAN NOT NULL DEFAULT true,
    "evening_recap_enabled"     BOOLEAN NOT NULL DEFAULT true,
    "quiet_hours_start"         TEXT NOT NULL DEFAULT '21:00',
    "quiet_hours_end"           TEXT NOT NULL DEFAULT '07:00',
    "timezone"                  TEXT NOT NULL DEFAULT 'UTC',
    "updated_at"                TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "NotificationPreference_user_id_key" ON "NotificationPreference"("user_id");

-- CreateIndex
CREATE INDEX "NotificationPreference_user_id_idx" ON "NotificationPreference"("user_id");

-- CreateTable
CREATE TABLE "NotificationLog" (
    "id"         TEXT NOT NULL,
    "user_id"    TEXT NOT NULL,
    "type"       TEXT NOT NULL,
    "unmutable"  BOOLEAN NOT NULL DEFAULT false,
    "dedupe_key" TEXT NOT NULL,
    "deep_link"  TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "NotificationLog_user_id_type_dedupe_key_key" ON "NotificationLog"("user_id", "type", "dedupe_key");

-- CreateIndex
CREATE INDEX "NotificationLog_user_id_created_at_idx" ON "NotificationLog"("user_id", "created_at");

-- CreateTable
CREATE TABLE "Referral" (
    "id"                  TEXT NOT NULL,
    "referrer_user_id"    TEXT NOT NULL,
    "relationship_type"   TEXT NOT NULL,
    "channel"             TEXT NOT NULL,
    "script_text"         TEXT NOT NULL,
    "cfe_outcome"         "CFEOutcome",
    "cfe_cleared"         BOOLEAN NOT NULL DEFAULT false,
    "referred_contact_id" TEXT,
    "created_at"          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Referral_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Referral_referrer_user_id_idx" ON "Referral"("referrer_user_id");

-- CreateIndex
CREATE INDEX "Referral_referred_contact_id_idx" ON "Referral"("referred_contact_id");
