-- T-23 (Memory Jogger, master-spec §7.4 "a jogger that surfaces an existing contact increments a
-- counter and skips"): adds the single additive `Contact.memory_jogger_skip_count` column. When the
-- Memory Jogger's name-capture flow resolves a rep-entered name to an ALREADY-Vaulted contact
-- (instead of creating a new one), this counter increments instead of a duplicate row being
-- created — see src/services/warm-market/memory-jogger.service.ts's `captureNamedMemory`. No other
-- model is touched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716120000_t12_account_security and
-- 20260717120000_t22_import_batch. This is the exact diff `prisma migrate dev` would generate from
-- the schema change (one new NOT NULL column with a default, on Contact only).

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN "memory_jogger_skip_count" INTEGER NOT NULL DEFAULT 0;
