-- T-36 (master-spec §10.3, SC5 launch gate) — Deliverability provisioning: A2P 10DLC (brand +
-- campaign registration + platform-number provisioning) and email domain authentication + sender
-- warm-up. Purely additive: five new tables + four new enums, no existing column/table/enum is
-- altered or dropped.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716090000_add_audit_hash_chain and
-- 20260718170000_t31_agent_kill_switch.

-- CreateEnum
CREATE TYPE "A2PProvisioningStatus" AS ENUM ('UNREGISTERED', 'PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "PlatformNumberStatus" AS ENUM ('UNPROVISIONED', 'PROVISIONED', 'ASSIGNED', 'RELEASED');

-- CreateEnum
CREATE TYPE "EmailAuthRecordStatus" AS ENUM ('NOT_CONFIGURED', 'PENDING', 'VERIFIED', 'FAILED');

-- CreateEnum
CREATE TYPE "EmailWarmupStage" AS ENUM ('NOT_STARTED', 'RAMPING', 'WARMED', 'PAUSED');

-- CreateTable
CREATE TABLE "A2PBrandRegistration" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "twilio_brand_sid" TEXT,
    "status" "A2PProvisioningStatus" NOT NULL DEFAULT 'UNREGISTERED',
    "entity_type" TEXT,
    "failure_reason" TEXT,
    "submitted_at" TIMESTAMPTZ,
    "approved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "A2PBrandRegistration_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "A2PBrandRegistration_organization_id_key" ON "A2PBrandRegistration"("organization_id");

-- CreateIndex
CREATE INDEX "A2PBrandRegistration_status_idx" ON "A2PBrandRegistration"("status");

-- CreateTable
CREATE TABLE "A2PCampaignRegistration" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "twilio_campaign_sid" TEXT,
    "status" "A2PProvisioningStatus" NOT NULL DEFAULT 'UNREGISTERED',
    "use_case" TEXT NOT NULL,
    "opt_in_language" TEXT NOT NULL,
    "throughput_tier" TEXT,
    "failure_reason" TEXT,
    "submitted_at" TIMESTAMPTZ,
    "approved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "A2PCampaignRegistration_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "A2PCampaignRegistration_organization_id_key" ON "A2PCampaignRegistration"("organization_id");

-- CreateIndex
CREATE INDEX "A2PCampaignRegistration_status_idx" ON "A2PCampaignRegistration"("status");

-- CreateTable
CREATE TABLE "PlatformPhoneNumber" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "twilio_phone_number_sid" TEXT,
    "campaign_registration_id" TEXT,
    "status" "PlatformNumberStatus" NOT NULL DEFAULT 'UNPROVISIONED',
    "released_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "PlatformPhoneNumber_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PlatformPhoneNumber_phone_number_key" ON "PlatformPhoneNumber"("phone_number");

-- CreateIndex
CREATE INDEX "PlatformPhoneNumber_organization_id_idx" ON "PlatformPhoneNumber"("organization_id");

-- CreateIndex
CREATE INDEX "PlatformPhoneNumber_organization_id_status_idx" ON "PlatformPhoneNumber"("organization_id", "status");

-- CreateTable
CREATE TABLE "EmailDomainAuthentication" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "sending_domain" TEXT NOT NULL,
    "spf_status" "EmailAuthRecordStatus" NOT NULL DEFAULT 'NOT_CONFIGURED',
    "dkim_status" "EmailAuthRecordStatus" NOT NULL DEFAULT 'NOT_CONFIGURED',
    "dmarc_status" "EmailAuthRecordStatus" NOT NULL DEFAULT 'NOT_CONFIGURED',
    "last_checked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "EmailDomainAuthentication_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EmailDomainAuthentication_organization_id_sending_domain_key" ON "EmailDomainAuthentication"("organization_id", "sending_domain");

-- CreateIndex
CREATE INDEX "EmailDomainAuthentication_organization_id_idx" ON "EmailDomainAuthentication"("organization_id");

-- CreateTable
CREATE TABLE "EmailWarmupPlan" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "sending_domain" TEXT NOT NULL,
    "stage" "EmailWarmupStage" NOT NULL DEFAULT 'NOT_STARTED',
    "started_at" TIMESTAMPTZ,
    "current_day" INTEGER NOT NULL DEFAULT 0,
    "daily_volume_cap" INTEGER NOT NULL DEFAULT 0,
    "target_daily_volume" INTEGER NOT NULL DEFAULT 0,
    "sent_today" INTEGER NOT NULL DEFAULT 0,
    "last_send_date" TEXT,
    "paused_reason" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "EmailWarmupPlan_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EmailWarmupPlan_organization_id_sending_domain_key" ON "EmailWarmupPlan"("organization_id", "sending_domain");

-- CreateIndex
CREATE INDEX "EmailWarmupPlan_organization_id_idx" ON "EmailWarmupPlan"("organization_id");
