-- T-12 (account security, master-spec §16.4/§18.10): adds the single new column session-hijack
-- revocation needs — `User.security_version` — a monotonically-bumped counter snapshotted into a
-- session's JWT at sign-in and compared against the live value on each security-sensitive check
-- (src/lib/auth/session-security.ts). Bumping it (on "sign out everywhere" or a privilege/role
-- change) invalidates every previously issued JWT at once without needing a server-side session
-- table, since NextAuth's Credentials+JWT flow (T-04) never persists Session rows.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same hand-authored-SQL convention established by 20260715140000_add_legal_hold and
-- 20260715212208_add_licensing_state_machine. This is the exact diff `prisma migrate dev` would
-- generate from the schema change (one new NOT NULL column with a default, on User only).

-- AlterTable
ALTER TABLE "User" ADD COLUMN "security_version" INTEGER NOT NULL DEFAULT 0;
