-- T-31 (master-spec §4.5/§4.6) — the kill-switch state table: PLATFORM (singleton, scope_id =
-- 'GLOBAL'), ORG (scope_id = Organization.id), or REP (scope_id = User.id). Purely additive: a new
-- table only, no existing column/table/enum is altered or dropped. Budget CEILINGS are not
-- persisted (computed in code from User.access_tier x User.intensity_setting, or a documented org/
-- platform constant); live SPEND is read from the existing AgentRun.cost_cents roll-up. This table
-- only persists whether a kill-switch is currently tripped, so state survives across requests/
-- instances and is toggleable via a session-gated, ownership-checked route.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716090000_add_audit_hash_chain and
-- 20260718100000_t29r_contact_jurisdiction / 20260718160000_t29r2_needs_jurisdiction_tier.

-- CreateTable
CREATE TABLE "AgentKillSwitch" (
    "id" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "scope_id" TEXT NOT NULL,
    "tripped" BOOLEAN NOT NULL DEFAULT false,
    "reason" TEXT,
    "tripped_by" TEXT,
    "tripped_at" TIMESTAMPTZ,
    "cleared_by" TEXT,
    "cleared_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "AgentKillSwitch_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AgentKillSwitch_scope_scope_id_key" ON "AgentKillSwitch"("scope", "scope_id");

-- CreateIndex
CREATE INDEX "AgentKillSwitch_scope_scope_id_tripped_idx" ON "AgentKillSwitch"("scope", "scope_id", "tripped");
