-- T-34 (master-spec §9.7 "the two ratios", §9.8 "The Shift"): two new, purely additive tables —
-- LearningState (durable per-rep Agent's Ratio / Field Trainer's Ratio + the LEARNING/SHIFTING/
-- SHIFTED 20:5:1 learning-state status) and ShiftSession (durable per-rep-per-day bounded-ritual
-- state: phase, stack position, accumulated elapsed seconds, streak, grace day, reflection). No
-- existing table, column, or enum is altered or dropped.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716120000_t12_account_security,
-- 20260717160000_t26_harvest_method, and 20260718170000_t31_agent_kill_switch.

-- CreateTable
CREATE TABLE "LearningState" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'LEARNING',
    "agent_introductions" INTEGER NOT NULL DEFAULT 0,
    "agent_responses" INTEGER NOT NULL DEFAULT 0,
    "agent_appointments_set" INTEGER NOT NULL DEFAULT 0,
    "agent_confirmed_shows" INTEGER NOT NULL DEFAULT 0,
    "trainer_appointments_run" INTEGER NOT NULL DEFAULT 0,
    "trainer_closes" INTEGER NOT NULL DEFAULT 0,
    "computed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "LearningState_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "LearningState_user_id_key" ON "LearningState"("user_id");

-- CreateIndex
CREATE INDEX "LearningState_user_id_idx" ON "LearningState"("user_id");

-- CreateTable
CREATE TABLE "ShiftSession" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "session_date" TEXT NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "phase" TEXT NOT NULL DEFAULT 'OPEN',
    "stack_position" INTEGER NOT NULL DEFAULT 0,
    "skip_counts" JSONB NOT NULL DEFAULT '{}',
    "accumulated_seconds" INTEGER NOT NULL DEFAULT 0,
    "last_resumed_at" TIMESTAMPTZ(6),
    "streak_count" INTEGER NOT NULL DEFAULT 0,
    "grace_day_used" BOOLEAN NOT NULL DEFAULT false,
    "reflection_text" TEXT,
    "recap_approvals" INTEGER NOT NULL DEFAULT 0,
    "recap_confirmations" INTEGER NOT NULL DEFAULT 0,
    "recap_logs" INTEGER NOT NULL DEFAULT 0,
    "completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ShiftSession_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ShiftSession_user_id_session_date_key" ON "ShiftSession"("user_id", "session_date");

-- CreateIndex
CREATE INDEX "ShiftSession_user_id_idx" ON "ShiftSession"("user_id");
