-- T-29R2 (WP03 gate remediation follow-up, master-spec §7.6 "needs info" pattern mirrored for
-- §8.2 eligibility): adds a single additive `ReadinessTier` enum value, `NEEDS_JURISDICTION`,
-- distinguishing an UNKNOWN contact jurisdiction (regulated rep, a remediable data gap — surfaced
-- as a data-completion prompt) from a CONFIRMED-unlicensed jurisdiction (still `EXCLUDED`,
-- unchanged). No existing enum value, column, or table is altered or dropped — this migration only
-- adds.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716090000_add_audit_hash_chain (which also
-- adds a single enum value via `ALTER TYPE ... ADD VALUE`) and 20260718100000_t29r_contact_jurisdiction.

-- AlterEnum
ALTER TYPE "ReadinessTier" ADD VALUE 'NEEDS_JURISDICTION';
