-- T-45 (WP09 — Team Calendar & Upline Dashboard, master-spec §14, uiux §5.9). Purely additive: two
-- new nullable columns on the existing "Appointment" table, and five new tables. No existing
-- column, table, constraint, or enum value is altered or dropped.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset), following the same convention
-- established by prior hand-authored migrations in this repo (see
-- 20260720140000_t_r4_audit_hardening's header for the rationale).

-- AlterTable: Appointment — event_kind distinguishes "Closing Appointment" from other kinds this
-- table may carry in future; dossier carries the pre-event briefing (§14.3). Both nullable/defaulted
-- so every existing row keeps reading correctly with no backfill required.
ALTER TABLE "Appointment" ADD COLUMN "event_kind" TEXT DEFAULT 'closing_appointment';
ALTER TABLE "Appointment" ADD COLUMN "dossier" JSONB;

-- AlterTable: CalendarLink — a composite index supporting the per-user, per-provider sync lookups
-- (google-sync.service.ts / caldav-sync.service.ts).
CREATE INDEX "CalendarLink_user_id_provider_idx" ON "CalendarLink"("user_id", "provider");

-- CreateTable: CalendarBusyBlock — ingested busy/blocking windows (Google dual-sync read half +
-- CalDAV read-only), §14.1. No title/content column by construction (privacy: never surfaced to
-- upline as individual events, only as coarse aggregate zones).
CREATE TABLE "CalendarBusyBlock" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "external_ref" TEXT,
    "starts_at" TIMESTAMPTZ(6) NOT NULL,
    "ends_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "CalendarBusyBlock_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "CalendarBusyBlock_user_id_starts_at_idx" ON "CalendarBusyBlock"("user_id", "starts_at");
CREATE UNIQUE INDEX "CalendarBusyBlock_user_id_provider_external_ref_key" ON "CalendarBusyBlock"("user_id", "provider", "external_ref");

-- CreateTable: CoachingSession — the "Coaching Session (high — rep + upline)" event type (§14.2),
-- with the same deterministic slot_lock_id discipline as Appointment (§14.3/§18.4 double-booking
-- race safety).
CREATE TABLE "CoachingSession" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "rep_id" TEXT NOT NULL,
    "trainer_id" TEXT NOT NULL,
    "starts_at" TIMESTAMPTZ(6) NOT NULL,
    "ends_at" TIMESTAMPTZ(6) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PROPOSED',
    "slot_lock_id" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "CoachingSession_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "CoachingSession_slot_lock_id_key" ON "CoachingSession"("slot_lock_id");
CREATE INDEX "CoachingSession_rep_id_idx" ON "CoachingSession"("rep_id");
CREATE INDEX "CoachingSession_trainer_id_idx" ON "CoachingSession"("trainer_id");
CREATE INDEX "CoachingSession_organization_id_idx" ON "CoachingSession"("organization_id");

-- CreateTable: EnterpriseSeatAssignment — enterprise ($25k/yr) seat-pool management (§14.5).
CREATE TABLE "EnterpriseSeatAssignment" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "assigned_user_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "assigned_by_user_id" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "EnterpriseSeatAssignment_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "EnterpriseSeatAssignment_organization_id_assigned_user_id_key" ON "EnterpriseSeatAssignment"("organization_id", "assigned_user_id");
CREATE INDEX "EnterpriseSeatAssignment_organization_id_idx" ON "EnterpriseSeatAssignment"("organization_id");

-- CreateTable: OrgAnalyticsNarrative — Opus 4.8, batched org-level analytic narratives (§14.5/§4.4).
CREATE TABLE "OrgAnalyticsNarrative" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "narrative_text" TEXT NOT NULL,
    "model_used" TEXT NOT NULL DEFAULT 'opus_4_8',
    "period_start" TIMESTAMPTZ(6) NOT NULL,
    "period_end" TIMESTAMPTZ(6) NOT NULL,
    "input_metrics" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OrgAnalyticsNarrative_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "OrgAnalyticsNarrative_organization_id_created_at_idx" ON "OrgAnalyticsNarrative"("organization_id", "created_at");

-- CreateTable: EnterpriseOrgConfig — the enterprise console's custom-onboarding + SSO config/status
-- surface (§14.5). See enterprise-console.service.ts for the stated SSO-federation deviation.
CREATE TABLE "EnterpriseOrgConfig" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "onboarding_welcome_message" TEXT,
    "onboarding_enabled_steps" JSONB,
    "sso_provider" TEXT,
    "sso_status" TEXT NOT NULL DEFAULT 'not_connected',
    "sso_metadata_url" TEXT,
    "updated_by_user_id" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "EnterpriseOrgConfig_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "EnterpriseOrgConfig_organization_id_key" ON "EnterpriseOrgConfig"("organization_id");
