-- T-29R (WP03 gate remediation, master-spec §8.2 "Excluded: state-unlicensed" tier / §8.1
-- eligibility): adds the single additive, nullable `Contact.jurisdiction` column — a two-letter US
-- state postal code, deliberately PLAINTEXT (see the schema.prisma doc comment on this column for
-- the full rationale: it is coarse categorical/structural data, not an encrypted-PII field like
-- first_name/last_name/phone/email/notes, mirroring how LicensingRecord.jurisdiction is already
-- treated as non-identifying status data elsewhere in this codebase). No other model is touched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716120000_t12_account_security,
-- 20260717120000_t22_import_batch, 20260717150000_t23_memory_jogger_skip_count, and
-- 20260717160000_t26_harvest_method.

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN "jurisdiction" TEXT;
