-- T-R16 (uiux AC-5.6-5, master-spec §9.2/§9.9): adds ONE additive, nullable `DraftMessage` column —
-- `approval_justification` — the rep's short justification, captured ONLY when approving a
-- CFE-FLAGGED (non-PASS, non-HELD) draft. Never set for a clean PASS approval or a HELD/blocked
-- draft (which cannot be approved from any UI path at all, AC-5.6-4); this is purely additive
-- UX-completeness for the already-permitted flagged-approve path — the fail-closed CFE gate itself
-- (ApprovalInboxService.approveDraft's PENDING-only check) is untouched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260718170000_t33_draft_decline_reason and
-- 20260721100000_t_r25_org_switch_event.

-- AlterTable
ALTER TABLE "DraftMessage" ADD COLUMN "approval_justification" TEXT;
