import { NextResponse } from 'next/server';

import { prisma } from '@/lib/prisma';
import { withOnboardingGate } from '@/lib/auth/onboarding-gate';
import { PrioritizedQueueService } from '@/services/harvest-method/prioritized-queue.service';

// T-26 (§8.3) — `GET /api/harvest-method/action-queue` (this codebase's equivalent of the master
// spec's `GET /api/v1/warm-market/action-queue`): readiness-sorted, tier-labeled, EXCLUDED contacts
// NEVER appear here (§8.2's own Excluded-tier row: "never" queue — the named critical failure
// "excluded-contact in queue"). Openers/why-text drafting (Sonnet 5, §8.3) is WP04's consumption of
// this data, not generated by this route — this build unit's scope is the method + readiness
// ENGINE. Empty until all three layers are complete (§8.3 "no short-circuit").
export const dynamic = 'force-dynamic';

export const GET = withOnboardingGate(async (_req, _ctx, _session, identity) => {
  try {
    // Lazy: constructed per-request, not at module scope, so `next build`'s page-data collection
    // (which imports this module) never triggers the constructor's fail-closed
    // `getContactEncryptionKey()` default read (T-26 build-integration fix).
    const service = new PrioritizedQueueService();
    const user = await prisma.user.findUnique({ where: { id: identity.userId }, select: { rank: true } });
    const result = await service.getQueue(identity.userId, identity.orgType, {
      includeExcluded: false,
      rank: user?.rank ?? null,
    });
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
});
