import { NextResponse } from 'next/server';

import { prisma } from '@/lib/prisma';
import { withOnboardingGate } from '@/lib/auth/onboarding-gate';
import { PrioritizedQueueService } from '@/services/harvest-method/prioritized-queue.service';
import { AntiPatternBlockedError, rejectSortOverride } from '@/services/harvest-method/action-boundary';
import { DEFAULT_LOCALE, isLocale } from '@/lib/i18n/locale';

// T-26 (§8.3) — `GET /api/harvest-method/action-queue` (this codebase's equivalent of the master
// spec's `GET /api/v1/warm-market/action-queue`): readiness-sorted, tier-labeled, EXCLUDED contacts
// NEVER appear here (§8.2's own Excluded-tier row: "never" queue — the named critical failure
// "excluded-contact in queue"). Openers/why-text drafting (Sonnet 5, §8.3) is WP04's consumption of
// this data, not generated by this route — this build unit's scope is the method + readiness
// ENGINE. Empty until all three layers are complete (§8.3 "no short-circuit").
//
// T-27 (§8.5 "extraction-first sorting ... not a permitted sort mode"): this is the ONE ordering
// the action queue ever has (tier precedence, hidden score breaks ties only within a tier) — a
// caller requesting an alternate sort is REJECTED (400), never silently honored or silently
// ignored, before the request ever reaches the queue engine.
export const dynamic = 'force-dynamic';

export const GET = withOnboardingGate(async (req, _ctx, _session, identity) => {
  try {
    rejectSortOverride(req.nextUrl.searchParams);

    // Lazy: constructed per-request, not at module scope, so `next build`'s page-data collection
    // (which imports this module) never triggers the constructor's fail-closed
    // `getContactEncryptionKey()` default read (T-26 build-integration fix).
    const service = new PrioritizedQueueService();
    // T-57 RG8 (i18n) — `locale` selected in the SAME round trip as `rank` (no extra query) and
    // threaded through to `buildPrimericaVelocityContext`'s `urgencyNote`; fails soft to
    // `DEFAULT_LOCALE` on a missing/invalid `User.locale`, mirroring every other unit's fail-soft
    // locale-resolution convention (never blocks the queue on a locale hiccup).
    const user = await prisma.user.findUnique({ where: { id: identity.userId }, select: { rank: true, locale: true } });
    const result = await service.getQueue(identity.userId, identity.orgType, {
      includeExcluded: false,
      rank: user?.rank ?? null,
      locale: isLocale(user?.locale) ? user.locale : DEFAULT_LOCALE,
    });
    return NextResponse.json(result);
  } catch (error) {
    if (error instanceof AntiPatternBlockedError) {
      return NextResponse.json({ error: error.message, code: 'ANTI_PATTERN_BLOCKED', antiPattern: error.antiPattern }, { status: 400 });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
});
