-- T-39 (WP05 outreach sequences + edification/three-way handoff + objection tree + email +
-- conversation UI, master-spec §10.2 / §10.5 / §10.6 / §10.7; uiux §5.7 / §4.7). All ADDITIVE:
--   • Message gains the T-R16 fold-in approval attribution (`approved_by` / `approved_at`),
--     denormalized from the DraftMessage at send time so the conversation-timeline agent-sent badge
--     ("sent by your agent · approved by you [date]", uiux §4.7) reads off the immutable sent record.
--   • Three new tables — `OutreachSequence` + `OutreachSequenceStep` (the doctrine-safe multi-touch
--     cadence, §10.2; a step never sends itself — it dispatches its `draft_id` THROUGH the T-37 send
--     seam) and `ThreeWayHandoff` (the warm-intro-to-upline lifecycle, §10.6; visibility is org-gated
--     in the service layer on `upline_id` + `organization_id` — no FK crosses a rep/org boundary).
-- State/type columns are plain TEXT with an inline enumeration (matching this schema's existing
-- messaging-model convention — DraftMessage.approval_state, MessageThread.state, etc.), so no new
-- enum is added; `OutreachSequenceStep.channel` reuses the existing `MessageChannel` enum.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260717120000_t22_import_batch,
-- 20260719100000_t38_optout_quiet_tcpa, and 20260720120000_t37_send_hold_reason. This mirrors
-- exactly what `prisma migrate dev` would generate from the schema diff introduced by this change.

-- AlterTable (T-R16 fold-in: approval attribution on the immutable sent Message record)
ALTER TABLE "Message" ADD COLUMN "approved_by" TEXT;
ALTER TABLE "Message" ADD COLUMN "approved_at" TIMESTAMPTZ(6);

-- CreateTable
CREATE TABLE "OutreachSequence" (
    "id"                 TEXT NOT NULL,
    "user_id"            TEXT NOT NULL,
    "contact_id"         TEXT NOT NULL,
    "sequence_type"      TEXT NOT NULL,
    "state"              TEXT NOT NULL DEFAULT 'ACTIVE',
    "pause_reason"       TEXT,
    "current_step_index" INTEGER NOT NULL DEFAULT 0,
    "started_at"         TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"         TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "OutreachSequence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OutreachSequenceStep" (
    "id"               TEXT NOT NULL,
    "sequence_id"      TEXT NOT NULL,
    "step_index"       INTEGER NOT NULL,
    "channel"          "MessageChannel" NOT NULL,
    "scheduled_at"     TIMESTAMPTZ(6) NOT NULL,
    "status"           TEXT NOT NULL DEFAULT 'SCHEDULED',
    "draft_id"         TEXT,
    "send_hold_reason" TEXT,
    "sent_message_id"  TEXT,
    "dispatched_at"    TIMESTAMPTZ(6),
    "created_at"       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OutreachSequenceStep_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ThreeWayHandoff" (
    "id"                 TEXT NOT NULL,
    "user_id"            TEXT NOT NULL,
    "upline_id"          TEXT NOT NULL,
    "organization_id"    TEXT NOT NULL,
    "contact_id"         TEXT NOT NULL,
    "thread_id"          TEXT,
    "trigger_reason"     TEXT NOT NULL,
    "state"              TEXT NOT NULL DEFAULT 'INVITED',
    "invited_at"         TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "joined_at"          TIMESTAMP(3),
    "returned_at"        TIMESTAMP(3),
    "return_deadline_at" TIMESTAMPTZ(6) NOT NULL,
    "coached_next_step"  TEXT,
    "created_at"         TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"         TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ThreeWayHandoff_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OutreachSequence_user_id_idx" ON "OutreachSequence"("user_id");

-- CreateIndex
CREATE INDEX "OutreachSequence_contact_id_idx" ON "OutreachSequence"("contact_id");

-- CreateIndex
CREATE INDEX "OutreachSequence_user_id_state_idx" ON "OutreachSequence"("user_id", "state");

-- CreateIndex
CREATE INDEX "OutreachSequenceStep_sequence_id_step_index_idx" ON "OutreachSequenceStep"("sequence_id", "step_index");

-- CreateIndex
CREATE INDEX "OutreachSequenceStep_status_scheduled_at_idx" ON "OutreachSequenceStep"("status", "scheduled_at");

-- CreateIndex
CREATE INDEX "ThreeWayHandoff_user_id_idx" ON "ThreeWayHandoff"("user_id");

-- CreateIndex
CREATE INDEX "ThreeWayHandoff_upline_id_organization_id_idx" ON "ThreeWayHandoff"("upline_id", "organization_id");

-- CreateIndex
CREATE INDEX "ThreeWayHandoff_contact_id_idx" ON "ThreeWayHandoff"("contact_id");

-- CreateIndex
CREATE INDEX "ThreeWayHandoff_state_return_deadline_at_idx" ON "ThreeWayHandoff"("state", "return_deadline_at");

-- AddForeignKey
ALTER TABLE "OutreachSequenceStep" ADD CONSTRAINT "OutreachSequenceStep_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES "OutreachSequence"("id") ON DELETE CASCADE ON UPDATE CASCADE;
