-- T-R25 (remediation for WP08/T-49, master-spec §"taprooting" org-switch): adds the `OrgSwitchEvent`
-- table that WP08 defined in prisma/schema.prisma but never shipped a migration for. Purely
-- additive: no existing column, table, constraint, or enum value is altered or dropped. The
-- `OrgType` enum this table references already exists (created by
-- 20260715120420_evolve_to_spec_v3) — nothing to add there.
--
-- Why this was missing: `prisma generate` builds the Prisma Client straight from schema.prisma
-- regardless of the migrations directory, so org-switch unit/integration tests that use the
-- generated client (or an in-memory/mocked repository) passed without ever touching a real
-- Postgres instance. `prisma migrate deploy` against a real database, however, only ever applies
-- what's in prisma/migrations — so `OrgSwitchEvent` writes
-- (src/services/taprooting/org-switch.service.ts) would fail in any real deploy with
-- `relation "OrgSwitchEvent" does not exist`. This migration closes that schema↔migration drift;
-- see also the new `guard:migration-drift` postbuild guard (package.json /
-- scripts/verify-migration-drift.* ) added alongside this fix, which fails the build if this class
-- of gap recurs.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- by default in this build environment (DATABASE_URL intentionally unset), following the same
-- convention established by prior hand-authored migrations in this repo (see
-- 20260720140000_t_r4_audit_hardening's header for the rationale). This migration.sql is exactly
-- the output of
-- `prisma migrate diff --from-migrations prisma/migrations --to-schema-datamodel prisma/schema.prisma --shadow-database-url <local throwaway Postgres 16> --script`
-- run against the pre-fix migrations directory, and was additionally applied end-to-end
-- (full `prisma migrate deploy` chain from empty) against a throwaway local Postgres 16 instance as
-- part of this build, confirming the resulting `OrgSwitchEvent` table matches the Prisma Client
-- generated from schema.prisma with zero further drift.

-- CreateTable
CREATE TABLE "OrgSwitchEvent" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "from_org_type" "OrgType" NOT NULL,
    "to_org_type" "OrgType" NOT NULL,
    "archived_edge_count" INTEGER NOT NULL DEFAULT 0,
    "archived_milestone_count" INTEGER NOT NULL DEFAULT 0,
    "switched_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OrgSwitchEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OrgSwitchEvent_user_id_idx" ON "OrgSwitchEvent"("user_id");
