-- T-37 (WP05 SMS send paths, master-spec §10.1 / §10.8 / uiux §4.4): adds the single additive,
-- nullable `DraftMessage.send_hold_reason` column the unified send decision
-- (src/services/messaging/send/*) writes to when a dispatch is withheld at send time — the honest
-- "held for review — nothing was lost" (§5.2) evidence the rep-facing timeline surfaces, distinct
-- from the human `decline_reason` added in 20260718170000_t33_draft_decline_reason. Values:
-- OPTED_OUT | QUIET_HOURS | NO_TCPA_CONSENT | NOT_DELIVERABLE | NOT_CFE_CLEARED | NOT_APPROVED |
-- EDITED_AFTER_APPROVAL | CHANNEL_MISMATCH | TWILIO_UNCONFIGURED | NO_PLATFORM_NUMBER | NO_PHONE |
-- ERROR. Set on a held send; cleared to NULL on a successful send/handoff. No other model touched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260717120000_t22_import_batch,
-- 20260718170000_t33_draft_decline_reason, and 20260719100000_t38_optout_quiet_tcpa.

-- AlterTable
ALTER TABLE "DraftMessage" ADD COLUMN "send_hold_reason" TEXT;
