-- T-38 (master-spec §10.4 "Global opt-out & quiet hours (P0 — TCPA)"; §16.2 regulatory matrix "TCPA
-- | ... | Per-contact consent"): two small, purely additive changes. No existing table, column,
-- constraint, or enum is altered or dropped, and no existing row's meaning changes.
--
-- 1. `Contact.timezone` — nullable IANA timezone id, consumed by
--    src/services/compliance/quiet-hours/quiet-hours.ts to compute the recipient's LOCAL 8 AM–9 PM
--    quiet-hours window (§10.4). Absent on every pre-existing row; isWithinQuietHours() treats a
--    missing/invalid value as fail-CLOSED (within quiet hours -> blocked), never as UTC or the
--    rep's own zone.
--
-- 2. `ComplianceConsent.contact_id` (nullable) + `.version` (Int, default 1) — the TCPA
--    per-contact messaging-consent ledger (src/services/compliance/messaging-consent/) reuses this
--    existing WP11 ledger table rather than forking a parallel one, per the T-38 brief. Every
--    pre-existing row (the GDPR consent bridge, src/lib/onboarding/gdpr-consent.ts) keeps
--    `contact_id = NULL` and gets `version = 1` by default — both harmless, since nothing read
--    either column before this unit.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716120000_t12_account_security,
-- 20260717120000_t22_import_batch, 20260717150000_t23_memory_jogger_skip_count,
-- 20260718100000_t29r_contact_jurisdiction, and 20260718180000_t34_learning_state_and_shift.

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN "timezone" TEXT;

-- AlterTable
ALTER TABLE "ComplianceConsent" ADD COLUMN "contact_id" TEXT;
ALTER TABLE "ComplianceConsent" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;

-- CreateIndex
CREATE INDEX "ComplianceConsent_contact_id_consent_type_idx" ON "ComplianceConsent"("contact_id", "consent_type");
