-- T-12 CRITICAL fix (account security, master-spec §16.4): binds MFA step-up freshness to a
-- server-verified, SINGLE-USE proof instead of a client-supplied timestamp. Adds one nullable
-- column, `User.mfa_stepped_up_at` — written (server clock) by POST /api/auth/mfa/step-up only
-- after a real TOTP/recovery code verifies, and consumed (cleared) single-use by the jwt `update`
-- callback (src/lib/auth/options.ts) when it stamps the session's step-up freshness. Nullable with
-- no default: the normal resting state is "no unconsumed proof outstanding" (NULL).
--
-- Hand-authored, not generated by `prisma migrate dev` (no live Postgres in this build env;
-- DATABASE_URL intentionally unset) — same convention as 20260716120000_t12_account_security and
-- the migrations before it. This is the exact diff `prisma migrate dev` would emit for one new
-- nullable timestamptz column on User.

-- AlterTable
ALTER TABLE "User" ADD COLUMN "mfa_stepped_up_at" TIMESTAMPTZ(6);
