-- T-R36 — additive-only widening of the `OnboardingStep` enum so `OnboardingSession.current_step`
-- can durably persist the app's REAL 11-step vocabulary (`src/types/onboarding.ts`'s own
-- `OnboardingStep` TS enum / `ROLE_STEP_MAP`), not just the legacy 6-value subset
-- (REGISTER/ACCOUNT_TYPE/SEVEN_WHYS/GOAL_CARD/INTENSITY/COMPLETE) this enum shipped with. Before
-- this migration, a real onboarding session could never be persisted at the CONSENT_CAPTURE step —
-- the actual last step for every role (`ROLE_STEP_MAP`) and a value the live completion route
-- (`POST /api/onboarding/complete`) already compares `current_step` against — only an in-memory
-- test fixture could fake having reached it.
--
-- No existing enum value (REGISTER/ACCOUNT_TYPE/SEVEN_WHYS/GOAL_CARD/INTENSITY/COMPLETE) is
-- renamed, reordered relative to itself, or dropped, and no column/table is altered — this
-- migration only adds five new enum members. Every existing `OnboardingSession.current_step` value
-- in any pre-existing row remains valid and unchanged.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same convention already established by 20260716090000_add_audit_hash_chain (the other
-- hand-authored `ALTER TYPE ... ADD VALUE` migration in this repo) and
-- 20260715140000_add_legal_hold / 20260715212208_add_licensing_state_machine. This mirrors exactly
-- what `prisma migrate dev` would generate from the schema diff introduced by this change.
--
-- `ADD VALUE ... BEFORE/AFTER` positions each new member exactly where the widened
-- `prisma/schema.prisma` enum declares it, so the on-disk enum's ordinal order matches the schema
-- file byte-for-byte (Postgres enum ordinal order otherwise only matters for `<`/`>` comparisons,
-- which nothing in this codebase performs on `OnboardingStep`, but keeping it in the same order
-- makes `\dT+` / any future introspection read the same as the schema source).

-- AlterEnum
ALTER TYPE "OnboardingStep" ADD VALUE 'ROLE_ORG_CONTEXT' AFTER 'ACCOUNT_TYPE';
ALTER TYPE "OnboardingStep" ADD VALUE 'SPONSOR_MATCHING' AFTER 'INTENSITY';
ALTER TYPE "OnboardingStep" ADD VALUE 'FINRA_DISCLOSURE' AFTER 'SPONSOR_MATCHING';
ALTER TYPE "OnboardingStep" ADD VALUE 'CALENDAR_CONNECTION' AFTER 'FINRA_DISCLOSURE';
ALTER TYPE "OnboardingStep" ADD VALUE 'CONSENT_CAPTURE' AFTER 'CALENDAR_CONNECTION';
