-- T-22 (The Vault — master-spec §7.1 four ingestion modalities, §18.5 "interrupted import →
-- resumable, idempotent batch"): adds the single additive `ImportBatch` table, the import-job
-- checkpoint that makes a contact import resumable across a partial failure and idempotent across
-- a retry. No other model is touched — `Contact.import_batch_id` (already present, T-03) is a plain
-- scalar pointer into this new table, not a foreign key, matching this schema's established
-- convention of avoiding a back-reference array on Contact for every new import-adjacent entity.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260715140000_add_legal_hold,
-- 20260715212208_add_licensing_state_machine, 20260716120000_t12_account_security, and
-- 20260716150000_t15_incident_response. This mirrors exactly what `prisma migrate dev` would
-- generate from the schema diff introduced by this change.

-- CreateEnum
CREATE TYPE "ImportBatchStatus" AS ENUM ('IN_PROGRESS', 'COMPLETED');

-- CreateTable
CREATE TABLE "ImportBatch" (
    "id"                  TEXT NOT NULL,
    "user_id"             TEXT NOT NULL,
    "source"              TEXT NOT NULL,
    "idempotency_key"     TEXT NOT NULL,
    "status"              "ImportBatchStatus" NOT NULL DEFAULT 'IN_PROGRESS',
    "total_rows"          INTEGER NOT NULL DEFAULT 0,
    "cursor"              INTEGER NOT NULL DEFAULT 0,
    "imported_count"      INTEGER NOT NULL DEFAULT 0,
    "merged_count"        INTEGER NOT NULL DEFAULT 0,
    "minor_flagged_count" INTEGER NOT NULL DEFAULT 0,
    "error_rows"          JSONB,
    "created_at"          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"          TIMESTAMPTZ(6) NOT NULL,
    "completed_at"        TIMESTAMPTZ(6),

    CONSTRAINT "ImportBatch_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ImportBatch_user_id_idempotency_key_key" ON "ImportBatch"("user_id", "idempotency_key");

-- CreateIndex
CREATE INDEX "ImportBatch_user_id_idx" ON "ImportBatch"("user_id");

-- CreateIndex
CREATE INDEX "ImportBatch_user_id_status_idx" ON "ImportBatch"("user_id", "status");
