-- T-10 (immutable audit store, master-spec §5.6/§5.7/§16.1/§17.8): additive hash-chain
-- tamper-evidence columns on the existing AuditEntry table, plus a new `RECORDED` CFEOutcome enum
-- value for non-CFE audit events (licensing/data-rights/account-security) funneled into the same
-- unified store. No existing column, table, or enum value is altered or dropped — this migration
-- only adds.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same convention established by 20260715140000_add_legal_hold and
-- 20260715212208_add_licensing_state_machine. This mirrors exactly what `prisma migrate dev` would
-- generate from the schema diff introduced by this change (AuditEntry.sequence/prev_hash/
-- entry_hash + CFEOutcome.RECORDED only — no other model/enum is touched).

-- AlterEnum
ALTER TYPE "CFEOutcome" ADD VALUE 'RECORDED';

-- AlterTable
-- `sequence` is added as a Postgres SERIAL (auto-incrementing integer): a monotonic append-order
-- column independent of `created_at`, which the hash chain verifies against (see
-- src/services/compliance/audit/hash-chain.ts). Existing rows (if any) backfill via the sequence
-- in insertion order, matching `created_at` ordering for any pre-existing data.
ALTER TABLE "AuditEntry" ADD COLUMN     "sequence" SERIAL NOT NULL;
ALTER TABLE "AuditEntry" ADD COLUMN     "prev_hash" TEXT;
ALTER TABLE "AuditEntry" ADD COLUMN     "entry_hash" TEXT NOT NULL DEFAULT '';

-- CreateIndex
CREATE UNIQUE INDEX "AuditEntry_sequence_key" ON "AuditEntry"("sequence");
