-- T-47R (WP10 gate remediation, master-spec §15.7-8 chargeback AC): adds the single additive,
-- nullable `Subscription.stripe_customer_id` column + a lookup index. Purely additive: no
-- existing column, table, or enum is altered or dropped.
--
-- Why this column exists: `charge.dispute.created` (the Stripe chargeback webhook) only carries
-- the disputed CHARGE and CUSTOMER ids on its payload — never our internal user id or the Stripe
-- SUBSCRIPTION id. Before this migration, `Subscription` only stored `stripe_subscription_id`,
-- so a dispute event had no column to resolve back to a user/subscription at all; the chargeback
-- handling logic (`handleDisputeCreated` et al., chargeback.ts) was fully built and unit-tested
-- but had zero live callers because of exactly this gap. `onCheckoutCompleted`
-- (production-wiring.ts) now persists the Stripe customer id it already receives on
-- `checkout.session.completed`, and `onDisputeCreated` resolves a dispute's customer id through
-- this column to call the existing `handleDisputeCreated` on the real path.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same hand-authored-SQL convention established by 20260716120000_t12_account_security,
-- 20260718100000_t29r_contact_jurisdiction, and 20260720140000_t_r4_audit_hardening.

-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN "stripe_customer_id" TEXT;

-- CreateIndex
CREATE INDEX "Subscription_stripe_customer_id_idx" ON "Subscription"("stripe_customer_id");
