-- T-R5 (multi-instance shared store, master-spec §16.4/§18.10 launch-gate remediation): the
-- rate-limit / session-activity / login-history stores introduced by T-12 are process-local
-- (InMemory*Store) — correct on one instance, but on a multi-instance/serverless (Vercel) deploy
-- each instance keeps its own counters, so a distributed attacker can multiply their effective
-- attempt budget by the instance count. These three tables back a Postgres-backed, cluster-wide
-- implementation of T-12's already-swap-ready store interfaces (RateLimitStore,
-- SessionActivityStore, LoginHistoryStore) — additive only, no policy change (same caps/windows/
-- lockout math as before; see src/services/security/rate-limiter.ts,
-- src/lib/auth/session-security.ts, src/services/security/credential-stuffing.ts).
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same hand-authored-SQL convention established by 20260715140000_add_legal_hold and
-- 20260716120000_t12_account_security.

-- CreateTable: shared, cluster-wide rate-limit counters. `version` is an optimistic-concurrency
-- token — RateLimiter.check() does a versioned conditional UPDATE (WHERE version = <version read>)
-- so two instances racing to increment the same key never lose an update; a brand-new key relies on
-- this table's own primary-key constraint to turn a racing double-insert into a conflict instead
-- (see PostgresRateLimitStore.put in src/services/security/rate-limiter.ts).
CREATE TABLE "RateLimitCounter" (
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL,
    "window_start" TIMESTAMPTZ(6) NOT NULL,
    "violation_count" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "version" INTEGER NOT NULL DEFAULT 1,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "RateLimitCounter_pkey" PRIMARY KEY ("key")
);

-- CreateTable: shared session-activity ("last seen") timestamps, keyed by `userId:boundAt`
-- (src/lib/auth/session-security.ts `sessionActivityKey`). Plain last-write-wins upsert — no
-- optimistic concurrency needed (touch() only ever records "now", never a computed delta).
CREATE TABLE "SessionActivityRecord" (
    "key" TEXT NOT NULL,
    "last_activity_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "SessionActivityRecord_pkey" PRIMARY KEY ("key")
);

-- CreateTable: shared, append-only per-user login history feeding credential-stuffing anomaly
-- scoring (src/services/security/credential-stuffing.ts). INSERT-only — atomic by construction.
CREATE TABLE "LoginHistoryRecord" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "device_fingerprint_hash" TEXT NOT NULL,
    "ip_hash" TEXT NOT NULL,
    "at" TIMESTAMPTZ(6) NOT NULL,
    "outcome" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

    CONSTRAINT "LoginHistoryRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LoginHistoryRecord_user_id_at_idx" ON "LoginHistoryRecord"("user_id", "at");
