-- T-33 (WP04 Approval Inbox, master-spec §9.2 / uiux §5.6): adds the two additive, nullable
-- `DraftMessage` columns the decline-reason selector writes to ("not my voice / wrong person /
-- wrong time / other" + an optional free-text note) — both are only ever set when a draft is
-- declined. No other model is touched.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260717120000_t22_import_batch,
-- 20260717160000_t26_harvest_method, and 20260718100000_t29r_contact_jurisdiction.

-- AlterTable
ALTER TABLE "DraftMessage" ADD COLUMN "decline_reason" TEXT;
ALTER TABLE "DraftMessage" ADD COLUMN "decline_note" TEXT;
