-- T-R4 (WP11 audit hardening, master-spec §16.1 "immutability (append-only, signed audit)"):
-- layered DB-level immutability for the AuditEntry compliance trust spine, plus the new
-- AuditCheckpoint table used for external anchoring / tail-truncation detection
-- (src/services/compliance/audit/anchoring.ts). Purely additive: no existing column, table, or
-- enum value is altered or dropped.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same convention established by 20260716090000_add_audit_hash_chain and earlier
-- hand-authored migrations in this repo. This has been applied and manually verified against a
-- throwaway local Postgres 16 instance as part of this build (see the T-R4 build report) —
-- INSERT succeeds, UPDATE/DELETE on AuditEntry are rejected by the trigger below.
--
-- Why a trigger (not a Postgres RULE, and not a bare REVOKE):
--   - A RULE rewrites the query at parse time and, for UPDATE/DELETE, the closest equivalent is a
--     "DO INSTEAD NOTHING" rule — that makes the mutation a silent no-op (violates §17.7's "never
--     silently no-op" doctrine for evidence surfaces; a caller who thinks they redacted/corrected a
--     row would see success). A trigger that RAISEs is loud: the application sees a real thrown
--     error, exactly like the app-layer guard (no update()/delete() method exists on
--     `AuditRepository`/`PrismaAuditRepository` in the first place — see audit-service.ts) that
--     this trigger backstops.
--   - A bare `REVOKE UPDATE, DELETE ON "AuditEntry" FROM ...` is environment-fragile: it depends on
--     knowing the exact Postgres role the app connects as (varies Vercel Postgres / RDS / local dev
--     / CI), and a superuser or a role with `BYPASSRLS`-style elevated grants can still be granted
--     UPDATE/DELETE later without this migration knowing. A BEFORE UPDATE/DELETE trigger applies
--     regardless of which role issues the statement (short of literally disabling the trigger,
--     which itself requires elevated privilege and is a loud, auditable DDL event) — the strongest
--     portable option in a Prisma+Postgres migration per the T-R4 build brief.
--
-- Layered with the app-level guard already in place (T-10, unchanged by this migration):
--   `AuditRepository`/`PrismaAuditRepository`/`InMemoryAuditRepository` expose ONLY
--   `append`/`query`/`getById`/`getChainTail` — there is no `update`/`delete` method anywhere in
--   the TypeScript surface for a caller to even attempt to call. This trigger is the second,
--   independent layer: even a future bug that adds a raw `prisma.auditEntry.update(...)` call, or a
--   compromised app path that talks to Postgres directly bypassing the app layer entirely, still
--   cannot mutate or delete a row — Postgres itself refuses at the DB level.

-- CreateTable
CREATE TABLE "AuditCheckpoint" (
    "id" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "head_entry_hash" TEXT NOT NULL,
    "entry_count" INTEGER NOT NULL,
    "checkpoint_hash" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditCheckpoint_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AuditCheckpoint_created_at_idx" ON "AuditCheckpoint"("created_at");

-- CreateIndex
CREATE INDEX "AuditCheckpoint_sequence_idx" ON "AuditCheckpoint"("sequence");

-- DB-level immutability trigger function. Shared by AuditEntry and AuditCheckpoint (both are
-- compliance trust-spine tables under the same append-only/immutable requirement). RAISEs — the
-- statement aborts and the calling transaction sees a real Postgres error — rather than silently
-- doing nothing.
CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'audit hardening (T-R4): % is not permitted on "%" — this table is append-only and immutable at the database level (master-spec §16.1)', TG_OP, TG_TABLE_NAME
    USING ERRCODE = 'raise_exception';
  RETURN NULL; -- unreachable (RAISE EXCEPTION aborts the statement), kept for clarity/lint-friendliness
END;
$$ LANGUAGE plpgsql;

-- AuditEntry: block UPDATE and DELETE outright. INSERT (append) is untouched and remains fully
-- allowed — this is the "append-only" enforcement, not a read-only/frozen table.
CREATE TRIGGER audit_entry_block_update
  BEFORE UPDATE ON "AuditEntry"
  FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

CREATE TRIGGER audit_entry_block_delete
  BEFORE DELETE ON "AuditEntry"
  FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

-- AuditCheckpoint: same append-only/immutable posture — an anchoring checkpoint that could itself
-- be edited or removed would defeat the tail-truncation detection it exists to provide.
CREATE TRIGGER audit_checkpoint_block_update
  BEFORE UPDATE ON "AuditCheckpoint"
  FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

CREATE TRIGGER audit_checkpoint_block_delete
  BEFORE DELETE ON "AuditCheckpoint"
  FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();
