// T-41 (WP06 §11.1-§11.4, §11.2 layers 1-2) — Claude-only content drafting + the regenerate-on-
// violation loop. Sonnet 5 for every draft (§11.1 "Drafts generated by Sonnet 5"); Claude-only,
// fail-closed (§0.3): this module calls `AgentModelClient.generate` — the SAME injected boundary
// WP04's agent runtime uses (src/services/agent-runtime/claude) — and NEVER constructs a client or
// reads a key itself. A missing key / transport failure / timeout THROWS (MissingClaudeCredentialError
// / AgentModelError / AgentModelTimeoutError, all re-exported from that module) and is left
// UNCAUGHT here — callers (content-batch.service.ts, launch-kit.service.ts) catch it exactly like
// agent-runtime.ts catches it and mark the affected item(s) HELD, never a silent stub.
//
// §11.2 doctrine enforcement, layers 1-2: layer 1 (negative constraint) is baked into every system
// prompt by prompt-library.ts; layer 2 (post-generation scan + regenerate) is `runDoctrineChecks`
// below, composing doctrine-guard.ts's vocabulary/anti-pattern/tone-gate scans. Layer 3 (the CFE
// publication gate) is NOT called here — it is the caller's job (content-item.service.ts), exactly
// mirroring how agent-runtime.ts's handlers never call the CFE themselves either.

import type { AgentModelClient } from '@/services/agent-runtime/claude';
import { ClaudeModelTier } from '@/services/agent-runtime/runtime-model-map';
import {
  detectMassPersonalization as detectMassPersonalizationImpl,
  HaikuToneGateClassifier,
  scanDeterministicAntiPatterns,
  scanVocabulary,
  type ToneGateClassifierClient,
} from './doctrine-guard';
import { regenerationCorrectionNote } from './prompt-library';

export interface DraftShape {
  headline?: string;
  body: string;
  imageConceptPrompt?: string;
}

export interface GeneratedDraft extends DraftShape {
  vocabClean: boolean;
  doctrineNotes: string[];
  modelUsed: ClaudeModelTier;
  modelId: string;
  tokenInput: number;
  tokenOutput: number;
  attempts: number;
}

export interface GenerationDeps {
  modelClient: AgentModelClient;
  toneGate?: ToneGateClassifierClient;
}

export interface GenerationRequest {
  systemPrompt: string;
  userPrompt: string;
  parse: (raw: string) => DraftShape;
  maxAttempts?: number;
  maxTokens?: number;
}

/** Layer 2: runs the full WP06 doctrine scan over one candidate body. Fail-closed — a thrown tone-
 *  gate error (missing key, transport, malformed verdict) is NOT swallowed; it propagates so the
 *  caller treats this exactly like a CFE hold rather than silently skipping the tone check. */
export async function runDoctrineChecks(
  body: string,
  toneGate: ToneGateClassifierClient
): Promise<{ clean: boolean; reasons: string[] }> {
  const reasons: string[] = [];

  const vocab = scanVocabulary(body);
  if (!vocab.clean) {
    for (const v of vocab.violations) {
      reasons.push(`forbidden term "${v.forbidden}" — use "${v.replacement}" instead`);
    }
  }

  const antiPatterns = scanDeterministicAntiPatterns(body);
  if (!antiPatterns.clean) {
    for (const v of antiPatterns.violations) {
      reasons.push(`${v.kind.replace(/_/g, ' ')}: "${v.match}"`);
    }
  }

  // Semantic tone gate — MUST run and MUST NOT be caught here (fail-closed §0.3).
  const tone = await toneGate.classify(body);
  if (!tone.clean) {
    if (!tone.leadsWithRelationship) reasons.push('does not lead with relationship');
    if (!tone.treatsAudienceAsCommunity) reasons.push('does not treat the audience as community');
    if (!tone.reinforcesThreeLaws) reasons.push('does not reinforce (or contradicts) the Three Laws');
    if (tone.harvestHoarderFraming) reasons.push('Harvest-Hoarder framing — no base/community acknowledgment');
  }

  return { clean: reasons.length === 0, reasons };
}

/**
 * Draft on Sonnet 5, run the layer-2 doctrine scan, and regenerate (once, by default) on any
 * violation. If still dirty after `maxAttempts`, returns the last attempt with `vocabClean: false`
 * and the accumulated `doctrineNotes` — the caller (content-batch.service.ts / launch-kit.service.ts)
 * is responsible for refusing to advance a dirty draft past DRAFTING (§11.8-1: "zero contain
 * forbidden terms" in anything that reaches READY_FOR_REVIEW/SCHEDULED/PUBLISHED).
 */
export async function generateDoctrineCleanDraft(
  req: GenerationRequest,
  deps: GenerationDeps
): Promise<GeneratedDraft> {
  const maxAttempts = req.maxAttempts ?? 2;
  const toneGate = deps.toneGate ?? new HaikuToneGateClassifier(deps.modelClient);

  let userPrompt = req.userPrompt;
  let attempt = 0;
  let lastDraft: DraftShape = { body: '' };
  let lastResult: { clean: boolean; reasons: string[] } = { clean: false, reasons: [] };
  let modelId = '';
  let tokenInput = 0;
  let tokenOutput = 0;

  while (attempt < maxAttempts) {
    attempt++;
    const gen = await deps.modelClient.generate({
      tier: ClaudeModelTier.SONNET_5,
      systemPrompt: req.systemPrompt,
      userPrompt,
      maxTokens: req.maxTokens ?? 1400,
    });
    modelId = gen.modelId;
    tokenInput += gen.tokenInput;
    tokenOutput += gen.tokenOutput;
    lastDraft = req.parse(gen.text);

    lastResult = await runDoctrineChecks(lastDraft.body, toneGate);
    if (lastResult.clean) {
      return {
        ...lastDraft,
        vocabClean: true,
        doctrineNotes: [],
        modelUsed: ClaudeModelTier.SONNET_5,
        modelId,
        tokenInput,
        tokenOutput,
        attempts: attempt,
      };
    }

    // Regenerate from scratch with the violation fed back — never a light edit of dirty text.
    userPrompt = req.userPrompt + regenerationCorrectionNote(lastResult.reasons);
  }

  return {
    ...lastDraft,
    vocabClean: false,
    doctrineNotes: lastResult.reasons,
    modelUsed: ClaudeModelTier.SONNET_5,
    modelId,
    tokenInput,
    tokenOutput,
    attempts: attempt,
  };
}

/** §11.7/AC-6 batch-level cold-pitch/mass-personalization detection, re-exported here so callers
 *  generating a batch only need to import from this module. */
export const detectMassPersonalization = detectMassPersonalizationImpl;

// ─── Response parsers (tied to prompt-library.ts's exact prompt formats) ──────────────────────────

export function parseSocialPostResponse(raw: string): DraftShape {
  const marker = raw.search(/^IMAGE CONCEPT:/im);
  if (marker === -1) return { body: raw.trim() };
  const body = raw.slice(0, marker).trim();
  const imageConceptPrompt = raw.slice(marker).replace(/^IMAGE CONCEPT:/i, '').trim();
  return { body, imageConceptPrompt };
}

export function parseBlogResponse(raw: string): DraftShape {
  const lines = raw.trim().split('\n');
  const headline = lines[0]?.replace(/^#+\s*/, '').trim();
  const body = lines.slice(1).join('\n').trim() || raw.trim();
  return { headline, body };
}

export function parseEmailResponse(raw: string): DraftShape {
  const subjectMatch = raw.match(/^SUBJECT:\s*(.+)$/im);
  const headline = subjectMatch?.[1]?.trim();
  const body = subjectMatch ? raw.replace(subjectMatch[0], '').trim() : raw.trim();
  return { headline, body };
}

export function parseLaunchKitPieceResponse(raw: string): DraftShape {
  return { body: raw.trim() };
}
