-- T-26 (WP03 Harvest Method + readiness engine, master-spec §8.1-§8.2): two new, purely additive
-- tables — HarvestMethodState (per-rep three-layer progress) and ContactMethodProfile (per
-- rep+contact cluster/context/HIDDEN-readiness state) — plus their two enums (QualityCluster,
-- ReadinessTier). No existing table (User, Contact, OptOutRegistry, etc.) is altered.
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available in
-- this build environment (DATABASE_URL intentionally unset per build constraints), following the
-- same hand-authored-SQL convention established by 20260716120000_t12_account_security,
-- 20260717120000_t22_import_batch, and 20260717150000_t23_memory_jogger_skip_count.

-- CreateEnum
CREATE TYPE "QualityCluster" AS ENUM ('COMMUNITY_HUB', 'RISING_ACHIEVER', 'NATURAL_TEACHER', 'STEADY_BUILDER', 'HEART_OF_GOLD', 'QUIET_INFLUENCER');

-- CreateEnum
CREATE TYPE "ReadinessTier" AS ENUM ('A', 'B', 'SLOW_BURN', 'EXCLUDED');

-- CreateTable
CREATE TABLE "HarvestMethodState" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "vault_count_at_blank_canvas" INTEGER,
    "blank_canvas_completed_at" TIMESTAMPTZ(6),
    "blank_canvas_seed_count" INTEGER,
    "blank_canvas_soft_gate_confirmed" BOOLEAN NOT NULL DEFAULT false,
    "qualities_flip_selected_clusters" "QualityCluster"[] NOT NULL DEFAULT ARRAY[]::"QualityCluster"[],
    "qualities_flip_completed_at" TIMESTAMPTZ(6),
    "background_matching_completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "HarvestMethodState_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactMethodProfile" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "contact_id" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "needs_time" BOOLEAN NOT NULL DEFAULT false,
    "clusters" "QualityCluster"[] NOT NULL DEFAULT ARRAY[]::"QualityCluster"[],
    "career_stage" TEXT,
    "financial_situation" TEXT,
    "family_context" TEXT,
    "community_role" TEXT,
    "note" TEXT,
    "existing_licensee_flag" BOOLEAN NOT NULL DEFAULT false,
    "existing_licensee_acked_at" TIMESTAMPTZ(6),
    "readiness_score" INTEGER,
    "readiness_tier" "ReadinessTier",
    "queue_actioned_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ContactMethodProfile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "HarvestMethodState_user_id_key" ON "HarvestMethodState"("user_id");

-- CreateIndex
CREATE INDEX "HarvestMethodState_user_id_idx" ON "HarvestMethodState"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "ContactMethodProfile_user_id_contact_id_key" ON "ContactMethodProfile"("user_id", "contact_id");

-- CreateIndex
CREATE INDEX "ContactMethodProfile_user_id_idx" ON "ContactMethodProfile"("user_id");

-- CreateIndex
CREATE INDEX "ContactMethodProfile_user_id_readiness_tier_idx" ON "ContactMethodProfile"("user_id", "readiness_tier");
