-- T-11 (data rights, master-spec §16.3): the legal-hold mechanism that blocks deletion processing.
-- Adds the LegalHold table and an index to the pre-existing UserDataDeletion table so a HELD
-- deletion (blocked by an active hold) can be looked up efficiently by (user_id, status).
--
-- Hand-authored, not generated by `prisma migrate dev`: no live Postgres connection is available
-- in this build environment (DATABASE_URL intentionally unset per build constraints), following
-- the same hand-authored-SQL convention established by 20260715120420_evolve_to_spec_v3 and
-- 20260715130000_add_nextauth_tables. This mirrors exactly what `prisma migrate dev` would
-- generate from the schema diff introduced by this change (LegalHold model + UserDataDeletion
-- index only — no other model is touched, to stay out of the concurrent CFE build's schema
-- surface).

-- CreateTable
CREATE TABLE "LegalHold" (
    "id"         TEXT NOT NULL,
    "user_id"    TEXT NOT NULL,
    "status"     TEXT NOT NULL DEFAULT 'ACTIVE',
    "reason"     TEXT NOT NULL,
    "placed_by"  TEXT NOT NULL,
    "placed_at"  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lifted_by"  TEXT,
    "lifted_at"  TIMESTAMPTZ(6),
    "note"       TEXT,

    CONSTRAINT "LegalHold_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LegalHold_user_id_status_idx" ON "LegalHold"("user_id", "status");

-- CreateIndex
CREATE INDEX "UserDataDeletion_user_id_status_idx" ON "UserDataDeletion"("user_id", "status");
